# Generated by Django 5.0.6 on 2024-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='khabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(default='main_app/assets/img/reviewer-1.jpg', upload_to='main_app/assets/img/media')),
                ('tozih', models.CharField(default='پیش\u200cفرض', max_length=300)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
