# Generated by Django 5.0.6 on 2024-09-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khabar',
            name='mah',
            field=models.CharField(default='پیش\u200cفرض', max_length=15),
        ),
        migrations.AddField(
            model_name='khabar',
            name='rooz',
            field=models.IntegerField(default=1),
        ),
    ]
