# Generated by Django 5.0.6 on 2024-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_khabar_sal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khabar',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
