# Generated by Django 5.0.6 on 2024-09-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_khabar_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khabar',
            name='image',
            field=models.ImageField(null=True, upload_to='main_app/assets/img/media'),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='mah',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='tozih',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
