# Generated by Django 5.0.6 on 2024-09-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_khabar_image_alter_khabar_mah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khabar',
            name='safhe_khabar',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='khabar',
            name='image',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
