# Generated by Django 5.0.6 on 2024-09-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_khabar_safhe_khabar_alter_khabar_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khabar',
            old_name='safhe_khabar',
            new_name='safhekhabar',
        ),
    ]
