# Generated by Django 5.0.6 on 2024-09-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_detail_khabar'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_khabar',
            name='tozih_2',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='detail_khabar',
            name='tozih_3',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='detail_khabar',
            name='tozih_4',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
