# Generated by Django 5.0.6 on 2024-09-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_detail_khabar_tozih_2_detail_khabar_tozih_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_khabar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='detail_khabar',
            name='tozih',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='detail_khabar',
            name='tozih_2',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='detail_khabar',
            name='tozih_3',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='detail_khabar',
            name='tozih_4',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
