# Generated by Django 5.0.6 on 2024-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_detail_khabar_image_alter_detail_khabar_tozih_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akhbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان خبر')),
                ('thumbnail', models.ImageField(help_text='عکس با فرمت PNG و در اندازه 415 * 291 پیکسل باشد', upload_to='', verbose_name='تامنیل خبر')),
                ('mini_thumbnail', models.ImageField(help_text='عکس با فرمت PNG و در اندازه 90 * 86 پیکسل باشد', upload_to='', verbose_name='تامنیل کوچک خبر')),
                ('short_text', models.CharField(help_text='توضیح کوتاه در مورد خبر', max_length=4000, verbose_name='متن کوتاه')),
                ('day', models.IntegerField(default=1, verbose_name='روز')),
                ('month', models.CharField(default='مرداد', max_length=15, verbose_name='ماه')),
                ('year', models.IntegerField(default=1403, verbose_name='سال')),
                ('text_1', models.CharField(blank=True, max_length=4000, null=True, verbose_name='متن خبر 1')),
                ('text_2', models.CharField(blank=True, max_length=4000, null=True, verbose_name='متن خبر 2')),
                ('text_3', models.CharField(blank=True, max_length=4000, null=True, verbose_name='متن خبر 3')),
                ('text_4', models.CharField(blank=True, max_length=4000, null=True, verbose_name='متن خبر 4')),
                ('image', models.ImageField(blank=True, help_text='عکس با فرمت PNG و در اندازه 960 * 504 پیکسل باشد', null=True, upload_to='', verbose_name='عکس مرتبط با خبر')),
            ],
        ),
    ]
