# Generated by Django 5.0.6 on 2024-09-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_akhbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='akhbar',
            name='safhe_khabar',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='akhbar',
            name='image',
            field=models.ImageField(blank=True, help_text='عکس با فرمت PNG و در اندازه 960 در 504 پیکسل باشد', null=True, upload_to='', verbose_name='عکس مرتبط با خبر'),
        ),
    ]
