# Generated by Django 5.0.6 on 2024-09-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_akhbar_safhe_khabar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(verbose_name='تلفن همراه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('telegram_id', models.CharField(max_length=60, verbose_name='آیدی تلگرام')),
                ('instagram_id', models.CharField(max_length=60, verbose_name='آیدی اینستاگرام')),
                ('twitter_id', models.CharField(max_length=60, verbose_name='آیدی اینستاگرام')),
                ('logo', models.ImageField(help_text='لوگوی مخصوص سایت', upload_to='', verbose_name='لوگو')),
                ('instagram_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('instagram_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('instagram_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('instagram_image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('instagram_image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('instagram_image_6', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
