# Generated by Django 5.0.6 on 2024-09-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='footer_address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='آدرس پایین صفحه'),
        ),
        migrations.AddField(
            model_name='info',
            name='header_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس بالای صفحه'),
        ),
        migrations.AlterField(
            model_name='info',
            name='twitter_id',
            field=models.CharField(max_length=60, verbose_name='آیدی توییتر'),
        ),
    ]
