# Generated by Django 5.0.6 on 2024-09-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_info_footer_address_info_header_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='akhbar',
            name='thumbnail_2',
            field=models.ImageField(blank=True, help_text='عکس با فرمت PNG و در اندازه 415 * 291 پیکسل باشد', null=True, upload_to='', verbose_name='تامنیل خبر'),
        ),
    ]
