# Generated by Django 5.0.6 on 2024-09-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_akhbar_thumbnail_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akhbar',
            name='thumbnail_2',
            field=models.ImageField(blank=True, help_text='عکس با فرمت PNG و در اندازه 415 * 291 پیکسل باشد', null=True, upload_to='', verbose_name='تامنیل خبر 2'),
        ),
    ]
