# Generated by Django 5.0.6 on 2024-09-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_akhbar_thumbnail_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detail_khabar',
        ),
        migrations.DeleteModel(
            name='khabar',
        ),
        migrations.DeleteModel(
            name='khabar_home',
        ),
        migrations.DeleteModel(
            name='posthaye_digar',
        ),
    ]
