# Generated by Django 5.0.6 on 2024-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_delete_detail_khabar_delete_khabar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shahrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('hazine', models.CharField(max_length=30, verbose_name='شهریه')),
            ],
        ),
    ]
