# Generated by Django 5.0.6 on 2024-10-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_shahrie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shahrie',
            new_name='Shahrie_1',
        ),
    ]
