# Generated by Django 5.0.6 on 2024-10-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_rename_shahrie_shahrie_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shahrie_1',
            old_name='hazine',
            new_name='price',
        ),
    ]
