# Generated by Django 5.0.6 on 2024-10-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_rename_hazine_shahrie_1_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=70, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
            ],
        ),
    ]
