# Generated by Django 5.0.6 on 2024-10-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='instagram_image_1',
            field=models.ImageField(blank=True, help_text='عکس با فرمت PNG و در اندازه 162 در 162 پیکسل باشد', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram_image_2',
            field=models.ImageField(blank=True, help_text='عکس با فرمت PNG و در اندازه 162 در 162 پیکسل باشد', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram_image_3',
            field=models.ImageField(blank=True, help_text='عکس با فرمت PNG و در اندازه 162 در 162 پیکسل باشد', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram_image_4',
            field=models.ImageField(blank=True, help_text='عکس با فرمت PNG و در اندازه 162 در 162 پیکسل باشد', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram_image_5',
            field=models.ImageField(blank=True, help_text='عکس با فرمت PNG و در اندازه 162 در 162 پیکسل باشد', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram_image_6',
            field=models.ImageField(blank=True, help_text='عکس با فرمت PNG و در اندازه 162 در 162 پیکسل باشد', null=True, upload_to=''),
        ),
    ]
